version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-kodbox_app_1
      APP_PORT: 80

  app:
    image: kodcloud/kodbox
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/app-data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=kodbox
      - MYSQL_USER=kodbox_user
      - MYSQL_PASSWORD=kodbox_password
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.6
    restart: on-failure
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kodbox_root_password
      - MYSQL_DATABASE=kodbox
      - MYSQL_USER=kodbox_user
      - MYSQL_PASSWORD=kodbox_password
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1

  redis:
    image: redis:alpine
    restart: on-failure
    sysctls:
      - net.core.somaxconn=1024
      - vm.overcommit_memory=1
