version: '3.9'

services:
  backend:
    image: ghcr.io/simonwep/genesis:v1.3
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/.data:rw
    command: start
    ports:
      - "3957:3957"  # Port f√ºr den Backend-Service
    environment:
      - GENESIS_PORT
      - GENESIS_DB_PATH
      - GENESIS_CREATE_USERS
      - GENESIS_AUTHORIZED_URIS
      - GENESIS_JWT_SECRET
      - GENESIS_JWT_TOKEN_EXPIRATION
      - GENESIS_JWT_COOKIE_ALLOW_HTTP
      - GENESIS_USERNAME_PATTERN
      - GENESIS_KEY_PATTERN
      - GENESIS_DATA_MAX_SIZE
      - GENESIS_KEYS_PER_USER
      - GENESIS_GIN_MODE
      - GENESIS_LOG_MODE

  frontend:
    image: ghcr.io/simonwep/ocular:v1.5
    restart: on-failure

  nginx:
    image: nginx:1.24-alpine
    restart: on-failure
    ports:
      - "3958:80"  
    volumes:
      - ${APP_DATA_DIR}/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

