version: '3.9'

services:
  
  backend:
    image: ghcr.io/simonwep/genesis:v1.3
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/.data:rw
    environment:
      - GENESIS_PORT=${GENESIS_PORT}
      - GENESIS_DB_PATH=${GENESIS_DB_PATH}
      - GENESIS_CREATE_USERS=${GENESIS_CREATE_USERS}
      - GENESIS_AUTHORIZED_URIS
      - GENESIS_JWT_SECRET=${GENESIS_JWT_SECRET}
      - GENESIS_JWT_TOKEN_EXPIRATION=${GENESIS_JWT_TOKEN_EXPIRATION}
      - GENESIS_JWT_COOKIE_ALLOW_HTTP=${GENESIS_JWT_COOKIE_ALLOW_HTTP}
      - GENESIS_USERNAME_PATTERN=${GENESIS_USERNAME_PATTERN}
      - GENESIS_KEY_PATTERN=${GENESIS_KEY_PATTERN}
      - GENESIS_DATA_MAX_SIZE=${GENESIS_DATA_MAX_SIZE}
      - GENESIS_KEYS_PER_USER=${GENESIS_KEYS_PER_USER}
      - GENESIS_GIN_MODE=${GENESIS_GIN_MODE}
      - GENESIS_LOG_MODE=${GENESIS_LOG_MODE}
    container_name: denny-ocular_backend_1

  frontend:
    image: ghcr.io/simonwep/ocular:v1.5
    restart: on-failure
    ports:
      - '3956:80'  # Frontend auf Port 3956
    container_name: denny-ocular_frontend_1
