version: "3.2"

services:
  app_proxy:
    environment:
      APP_HOST: denny-dynamicqrcode_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  web:
    image:
    image: "giandonatoinverso/php-dynamic-qr-code:latest@sha256:dcb15194a5ff1725913399c1196127a7aae2b8d0ce177b41f3503c8754601240"
    restart: "unless-stopped"
    environment:
      TYPE: "docker"
      BASE_URL: "http://umbrel.local"
      DATABASE_HOST: "php-dynamic-qrcode-db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "qrcode"
      DATABASE_USER: "qrcode"
      DATABASE_PASSWORD: "sicheres_passwort"  # Passwort geändert
      DATABASE_PREFIX: ""
      DATABASE_CHARSET: "utf8"
    depends_on:
      - php-dynamic-qrcode-db
    volumes:
      - php_dynamic_qrcode_saved_qrcode_data:/var/www/html/saved_qrcode
    networks:
      - php-dynamic-qrcode-network

  php-dynamic-qrcode-db:
    image: "giandonatoinverso/php-dynamic-qr-code-db:latest"
    restart: "unless-stopped"
    volumes:
      - php_dynamic_qrcode_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "sicheres_root_passwort"  # Passwort geändert
      MYSQL_DATABASE: "qrcode"
      MYSQL_USER: "qrcode"
      MYSQL_PASSWORD: "sicheres_passwort"  # Passwort geändert
    networks:
      - php-dynamic-qrcode-network

volumes:
  php_dynamic_qrcode_db_data:
  php_dynamic_qrcode_saved_qrcode_data:

networks:
  php-dynamic-qrcode-network:
    driver: bridge
