version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-mazanoke_web_1
      APP_PORT: 80

  web:
    image: ghcr.io/civilblur/mazanoke:v1.0.1@sha256:9c00a3201dd942cb8b3d12c1c199e750f00c05cd1ea6f6445b28d76dc6cd9a58
    user: 1000:1000
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: on-failure