version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_web_1
      APP_PORT: 9200
  
  web:
    image: ghcr.io/opencloud-eu/ci-docker-desktop/appimage:latest
    volumes:
      - ${APP_DATA_DIR}/data/opencloud-config:/etc/opencloud
      - ${APP_DATA_DIR}/data/opencloud-data:/var/lib/opencloud
    restart: no
    environment:
      - OC_INSECURE=true
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - OC_URL=http://umbrel-2.local:9292
      - JWT_SECRET=8C1F54F950D5E3D126B9EF1081D48243
