version: "3.9"

services:
  db:
    container_name: MariaDB
    image: mariadb:10.3
    volumes:
    - ${APP_DATA_DIR}/facto_data/db_data:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: facto
      MYSQL_DATABASE: facto

  web:
    container_name: Facto
    depends_on: [db]
    command: bin/server
    image: nymanjens/facto:latest
    ports: ["9060:9000"]
    restart: on-failure
    environment:
      APPLICATION_SECRET: umbrelpass
      DATABASE_URL: jdbc:mysql://db:3306/facto?user=root&password=facto&disableMariaDbDriver
    volumes:
    - ${APP_DATA_DIR}/facto/facto_data/conf:/conf
