version: "3"

services:
  hatsu:
    container_name: hatsu
    image: ghcr.io/importantimport/hatsu:nightly
    restart: unless-stopped
    ports:
      - 3939:3939
    environment:
      - HATSU_DATABASE_URL=sqlite://hatsu.sqlite3
      - HATSU_DOMAIN=umbrel.local
      - HATSU_LISTEN_HOST=0.0.0.0
      - HATSU_PRIMARY_ACCOUNT=umbrel.local:3939
    volumes:
      - ./hatsu.sqlite3:/app/hatsu.sqlite3:rw
    # Optional: Sicherstellen, dass die .env-Datei korrekt verwendet wird, falls du sie später wieder aktivieren möchtest.
    # env_file:
    #   - .env
