version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-habitica_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
      
  web:
    image: awinterstein/habitica-server:5.34.0@sha256:ebc2299b324cc8496bfdd4d7d2b5b5bbc555c21068751dc1bfe734deb4b0fbbf
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/habitica
      - BASE_URL=http://umbrel-2.local:3944
      - INVITE_ONLY=true
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s

  mongo:
    image: mongo:5.0@sha256:54bcd8da3ea5eec561b68c605046c55c6b304387dc4c2bf5b3a5f5064fbb7495
    restart: on-failure
    command: ["--replSet", "rs", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')", "--host", "localhost"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    volumes:
      - ${APP_DATA_DIR}/mongo/db:/data/db:rw
      - ${APP_DATA_DIR}/mongo/dbconf:/data/configdb
