version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-filegator_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
  web:
    image: 'filegator/filegator:latest'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/images:/var/www/filegator/repository:rw
      - ${APP_DATA_DIR}/data/conf/configuration.php:/var/www/filegator/configuration.php
