---
version: "3.8"
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest@sha256:551a6cda96af9167a866bd283e12fd6d3b0a9ea433f10edc7c3d9663eca2ac92
    pull_policy: always
    # build: ./
    restart: on-failure
    ports:
      - '4100:4100'
    environment:
      # TZ: Europe/Paris
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data:/home/puter/.puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://umbrel.local:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
