version: "3.9"
services:
  app_proxy:
    environment:
      APP_HOST: denny-puter_web_1
      APP_PORT: 4100
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/heyputer/puter:main
    restart: on-failure
    environment:
      TZ: Europe/Berlin
      CONFIG_PATH: /config/config.json
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data:/data/.puter
      - ${APP_DATA_DIR}/config:/etc/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://umbrel.local:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
