---
version: "3.8"
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:sha-ec31007@sha256:46f0247c4b2a561b29548e275e343f14426f0f630c71155cbb58fad8343c3f92
    pull_policy: always
    # build: ./
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      PUID: 1000
      PGID: 1000
      APP_HOST: puter_web_1
      APP_PORT: 4100
      PROXY_AUTH_WHITELIST: "/api*"
    volumes:
      - ${APP_DATA_DIR}/data:/data/.puter
      - ${APP_DATA_DIR}/config:/volatile/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://umbrel.local:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
