version: "3.9"
services:
  init_config_permissions:
    image: busybox
    command: sh -c "chown -R 1000:1000 /config && chmod -R 775 /config"
    volumes:
      - ${APP_DATA_DIR}/config:/config
    restart: "no"

  app_proxy:
    environment:
      APP_HOST: denny-puter_web_1
      APP_PORT: 4100
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/heyputer/puter@sha256:f8dbc6a7eb97968603d2b72b4004427da631573966297eb2f48b40c4227b6852
    restart: on-failure
    environment:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data:/data/.puter
      - ${APP_DATA_DIR}/config:/config:rw
    depends_on:
      - init_config_permissions
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://umbrel.local:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
