version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-olivetin_web_1
      APP_PORT: 1337

  web:
    image: jamesread/olivetin:2025.3.23@sha256:4045896ae06ef897cb4ba16ac140ad7041f9d616e295f4c2fad1c7d1afd0b10c
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
