version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-twenty_server_1
      APP_PORT: 3000
      
  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - ${APP_DATA_DIR}/data/server-local-data:/tmp/server-local-data
      - ${APP_DATA_DIR}/data/docker-data:/tmp/docker-data
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"

  server:
    image: twentycrm/twenty:latest
    volumes:
      - ${APP_DATA_DIR}/data/server-local-data:/app/packages/twenty-server/.local-storage
      - ${APP_DATA_DIR}/data/docker-data:/app/docker-data
    #ports:
      # "2020:3000"
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      SERVER_URL: http://umbrel.local:3000
      REDIS_URL: redis://redis:6379

      STORAGE_TYPE: local
      STORAGE_S3_REGION: us-east-1
      STORAGE_S3_NAME: your-bucket-name
      STORAGE_S3_ENDPOINT: s3.amazonaws.com

      APP_SECRET: replace_me_with_a_random_string

    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  worker:
    image: twentycrm/twenty:latest
    volumes:
      - ${APP_DATA_DIR}/data/server-local-data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      SERVER_URL: http://umbrel.local:3000
      REDIS_URL: redis://redis:6379
      DISABLE_DB_MIGRATIONS: "true"

      STORAGE_TYPE: local
      STORAGE_S3_REGION: us-east-1
      STORAGE_S3_NAME: your-bucket-name
      STORAGE_S3_ENDPOINT: s3.amazonaws.com

      APP_SECRET: replace_me_with_a_random_string

    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16
    volumes:
      - ${APP_DATA_DIR}/data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -h localhost -d postgres
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    image: redis
    restart: always

volumes:
  docker-data:
  db-data:
  server-local-data:
