version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-bookstack_app_1
      APP_PORT: 80

  app:
    image: linuxserver/bookstack:24.12.1@sha256:6736133cee386851f3e3579b73bf42897da2e055ce2578ec6649179f29569857
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://umbrel.local:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=umbrelpass  
      - DB_DATABASE=bookstackapp
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/bookstack_app_data:/config
    restart: on-failure
    depends_on:
      - bookstack_db

  bookstack_db:
    image: linuxserver/mariadb:11.4.4@sha256:91f2ceb31088375bfd89c2b4857bca2a543d7a2e58ee281750aea97c366af5ce
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=umbrelpass
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=umbrelpass
    volumes:
      - ${APP_DATA_DIR}/data/bookstack_db_data:/config
    restart: on-failure
