---
  version: "2"
  
  volumes:
    app:
    db:
  
  services:
    app_proxy:
      environment:
        APP_HOST: denny-baikal_web_1
        APP_PORT: 80
        PROXY_AUTH_ADD: "false"
    app:
      image: ghcr.io/linuxserver/bookstack:latest
      environment:
        - PUID=1000
        - PGID=1000
        - APP_URL=http://umbrel-2.local:8875
        - DB_HOST=db
        - DB_PORT=3306
        - DB_USERNAME=bookstack
        - DB_PASSWORD=umbrelpass
        - DB_DATABASE=bookstackapp
        - APP_KEY=base64:agtE4ABZvOG9P7U7wM0Jzks+rTemAqlND6XUsyG/bHA=
      volumes:
        - ${APP_DATA_DIR}/data/bookstack_app_data:/config
      restart: on-failure
      depends_on:
        - db
  
    db:
      image: lscr.io/linuxserver/mariadb
      environment:
        - PUID=1000
        - PGID=1000
        - MYSQL_ROOT_PASSWORD=[root password]
        - TZ=America/Chicago
        - MYSQL_DATABASE=bookstackapp
        - MYSQL_USER=bookstack
        - MYSQL_PASSWORD=umbrelpass
      ports:
        - 3136:3306
      volumes:
        - ${APP_DATA_DIR}/data/bookstack_db_data:/config
      restart: on-failure
