version: '3.7'

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://umbrel-2.local:6875
      - APP_KEY=base64:YOUR_RANDOM_KEY_HERE
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USERNAME=bookstack
      - DB_PASSWORD=umbrelpass
      - DB_DATABASE=bookstackapp
      - QUEUE_CONNECTION= # Optional, leave empty or remove if you don't need it
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    ports:
      - 6875:80
    restart: on-failure
