version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: denny-chitchatter_web_1
      APP_PORT: 6667
      PROXY_AUTH_ADD: "false"

  web:
    image: noxcis/chitchatter:latest@sha256:bdb5d8bc7263cfff243708d45922b217d6ef810988c470f98526eaab68e115b8
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/:/data
