services:
  app_proxy:
    environment:
      APP_HOST: denny-wger_web_1
      APP_PORT: 8000

  web:
    image: wger/server:2.3-dev@sha256:5a8c6c93fb60eb974761c5701b574ba1ea7c5a8a4604de72d1f4dd5fbc7badab
    depends_on:
      - db
      - cache
    volumes:
      - ${APP_DATA_DIR}/data/static:/home/wger/static
      - ${APP_DATA_DIR}/data/media:/home/wger/media
    restart: on-failure

  db:
    image: postgres:15-alpine@sha256:ef9d1517df69c4d27dbb9ddcec14f431a2442628603f4e9daa429b92ae6c3cd1
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/postgres-data:/var/lib/postgresql/data/
    restart: on-failure

  cache:
    image: redis:7.4.2@sha256:6aafb7f25fc93c4ff74e99cff8e85899f03901bc96e61ba12cd3c39e95503c73
    volumes:
      - ${APP_DATA_DIR}/data/redis-data:/data
    restart: on-failure

  celery_worker:
    image: wger/server:2.3-dev@sha256:5a8c6c93fb60eb974761c5701b574ba1ea7c5a8a4604de72d1f4dd5fbc7badab
    command: /start-worker
    volumes:
      - ${APP_DATA_DIR}/data/media:/home/wger/media
    depends_on:
      - web
    restart: on-failure

  celery_beat:
    image: wger/server:2.3-dev@sha256:5a8c6c93fb60eb974761c5701b574ba1ea7c5a8a4604de72d1f4dd5fbc7badab
    command: /start-beat
    volumes:
      - ${APP_DATA_DIR}/data/celery-beat:/home/wger/beat/
    depends_on:
      - celery_worker
    restart: on-failure
