version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-checkmk_web_1
      APP_PORT: 5000

  web:
    image: checkmk/check-mk-raw:latest
    tmpfs: /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/checkmk:/omd/sites:rw
      - ${APP_DATA_DIR}/data/localtime:/etc/localtime:ro