version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-excalidraw
      APP_PORT: 3002

  web:
    image: ghcr.io/nextcloud-releases/whiteboard:v1.0.4@sha256:ebbc97490856f84325590d2acd7ea139ca4862e302d47202749c16fbafc08636 #excalidraw/excalidraw@sha256:fae667864717a415e7474b5f757ffb50e63a81cfc1a2fbcf905ecbd137d0dbba
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data/excalidraw

#https://github.com/excalidraw/excalidraw.git   - no arm64 image available
