version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: planka_planka_1
      APP_PORT: 1337

  planka:
    image: ghcr.io/plankanban/planka:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/user-avatars:/app/public/user-avatars
      - ${APP_DATA_DIR}/project-background-images:/app/public/project-background-images
      - ${APP_DATA_DIR}/attachments:/app/private/attachments
    environment:
      SELF_HOSTING_ENABLED: "true"
      PORT: 1337
      DB_HOST: db
      DB_PORT: 5432
      BASE_URL: http://umbrel.local:1337
      DATABASE_URL: postgresql://postgres@postgres/planka
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      POSTGRES_DB: planka
      POSTGRES_USER: planka
      POSTGRES_PASSWORD: planka
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: $APP_SEED
      DEFAULT_ADMIN_EMAIL: umbrel@planka.login # Do not remove if you want to prevent this user from being edited/deleted
      DEFAULT_ADMIN_PASSWORD: umbrelpass
      DEFAULT_ADMIN_NAME: Umbrel Home
      DEFAULT_ADMIN_USERNAME: umbrel
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16@sha256:1bf73ccae25238fa555100080042f0b2f9be08eb757e200fe6afc1fc413a1b3c
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: planka
      POSTGRES_USER: planka
      POSTGRES_PASSWORD: planka
      PGDATA: /var/lib/postgresql/data/pgdata
