version: '3'

services:
  app_proxy:
    environment:
      APP_HOST: planka_web_1
      APP_PORT: 1337
    networks:
      - planka-network

  web:
    container_name: planka_web_1
    image: ghcr.io/plankanban/planka:1.11.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/user-avatars:/app/public/user-avatars
      - ${APP_DATA_DIR}/project-background-images:/app/public/project-background-images
      - ${APP_DATA_DIR}/attachments:/app/private/attachments
    environment:
      - BASE_URL=http://umbrel.local:1337
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=notsecretkey
      - DEFAULT_ADMIN_EMAIL=umbrel@planka.login
      - DEFAULT_ADMIN_PASSWORD=umbrelpass
      - DEFAULT_ADMIN_NAME=Umbrel Home
      - DEFAULT_ADMIN_USERNAME=umbrel
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - planka-network

  postgres:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - planka-network

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:

networks:
  planka-network:
    driver: bridge
