version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-zipline_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  db:
    image: postgres:17.3@sha256:6e3358e46e34dae6c184f48fd06fe1b3dbf958ad5b83480031907e52b9ec2a7d
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "zipline", "-U", "ziplineuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    user: "1000:1000"
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: zipline
      POSTGRES_USER: ziplineuser
      POSTGRES_PASSWORD: ziplinepass
    restart: on-failure

  web:
    image: ghcr.io/diced/zipline:4.0.0@sha256:73351d7b653b2362895004398609adcfc60b2b7c9ad50b7cb488c8f4c36d4b3a
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3472"]
      interval: 30s 
      timeout: 10s  
      retries: 5
      start_period: 30s
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:3472
      NEXT_PUBLIC_BASE_URL: http://localhost:3472
      NEXTAUTH_SECRET: 3b449077187f1150082fb348796e97be22b57fefdbd4a7b18f575b51f65519b7
      DATABASE_URL: postgresql://ziplineuser:ziplinepass@db:5432/zipline
    user: "1000:1000"  
    volumes:
      - ./data/uploads:/zipline/uploads:rw
      - ./data/public:/zipline/public:rw
      - ./data/themes:/zipline/themes:rw
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
