version: '3.2'

services:
  app_proxy:
    environment:
      APP_HOST: denny-collabora_server_1
      APP_PORT: 9980
      PROXY_AUTH_ADD: "false"
  server:
    image: collabora/code:24.04.9.2.1@sha256:56fe61f51d7c3031f9727c06484d9e9242241704bf4b9cece89c7281a0e1e048
    restart: on-failure
    cap_add:
      - MKNOD
    environment:
      - VIRTUAL_HOST=umbrel.local
      - VIRTUAL_PORT=9980
      - username=admin
      - password=umbrel
      - domain=umbrel.local:9980
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true  # Deaktiviert SSL
