version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cheshire-cat_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  server:
    image: ghcr.io/cheshire-cat-ai/core:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/static:/app/cat/static:rw
      - ${APP_DATA_DIR}/plugins:/app/cat/plugins:rw
      - ${APP_DATA_DIR}/data:/app/cat/data:rw
