version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-superproductivity_web_1
      APP_PORT: 80
  web:
    image: johannesjo/super-productivity:v10.1.1@sha256:85abc19361a41122865981613d640ebb57ed8692f8e15e43882820f2bd1ec925
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
