version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-superproductivity_web_1
      APP_PORT: 80

  web:
    image: johannesjo/super-productivity:v10.2.3@sha256:d8df5fc62c04de4e17384150439a20be2265b500084e134b420436703894ad64
    restart: on-failure
    environment:
      - WEBDAV_BACKEND=denny-super-productivity_webdav_1
    depends_on:
      - webdav
      
  webdav:
    image: hacdias/webdav:v5.4@sha256:afa0a5a0e7dbe3d6040786777e837beb836d1919cdfe0099e640fce86c2fa3df
    environment:
    - WEBDAV_AUTH_USER=umbrel
    - WEBDAV_AUTH_PASSWORD=umbrel
    volumes:
      - ${APP_DATA_DIR}/data/webdav/webdav.yaml:/config.yml:ro
      - ${APP_DATA_DIR}/data/storage:/data
