version: '3.7'

services:
  frontend:
    image: itzmizzle/wagmi:frontend-latest
    container_name: wagmios-frontend
    ports:
      - "8555:5174"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://umbrel-2.local:8080
    networks:
      - wagmios-network
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/frontend_data:/app/data

  backend:
    image: itzmizzle/wagmi:backend-latest
    container_name: wagmios-backend
    ports:
      - "8980:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/backend_data:/app/data
    environment:
      - PORT=8980
      - WILLOW_URL=http://willow:5678
    networks:
      - wagmios-network

  willow:
    image: n8nio/n8n
    container_name: willow
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_DEFAULT_WORKFLOW_STATE=active
      - N8N_LOG_LEVEL=info
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=willow_memories
      - DB_POSTGRESDB_USER=willow
      - DB_POSTGRESDB_PASSWORD=wagmios
    volumes:
      - ${APP_DATA_DIR}/willow_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - wagmios-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_USER=willow
      - POSTGRES_PASSWORD=wagmios
      - POSTGRES_DB=willow_memories
    volumes:
      - ${APP_DATA_DIR}/postgres_data:/var/lib/postgresql/data
    networks:
      - wagmios-network

networks:
  wagmios-network:
    driver: bridge
