version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: denny-traggo_web_1
      APP_PORT: 3083
      PROXY_AUTH_ADD: "false"

  web:
    image: traggo/server:latest
    restart: on-failure
    environment:
      TRAGGO_DEFAULT_USER_NAME: "admin"
      TRAGGO_DEFAULT_USER_PASS: "umbrel"
    volumes:
      - ${APP_DATA_DIR}/traggodata:/opt/traggo/data
