---
version: "2.1"
services:
   webtop:
      image: ghcr.io/linuxserver/webtop:alpine-mate
      container_name: webtop
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/Berlin
      volumes:
         - ${APP_DATA_DIR}/webtop/config:/config
      ports:
         - 3020:3000
      shm_size: "1gb"
      restart: unless-stopped
