version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-overleaf_web_1
      APP_PORT: 80

  web:
    image: sharelatex/sharelatex:5.3.0@sha256:126606213d8be24ad38b658ea95358e2584b17675ffcb8ec7e99625e9dd42e90
    restart: on-failure
    depends_on:
      - mongo
      - redis
    stop_grace_period: 60s
    volumes:
      - ${APP_DATA_DIR}/data/sharelatex_data:/var/lib/overleaf
    environment:
      OVERLEAF_APP_NAME: Overleaf
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      SANDBOXED_COMPILES: 'false'

  mongo:
    image: nertworkweb/mongodb-no-avx:latest@sha256:35f6463c359dbfbada9a53104b64547d6cba514fae3b380ff9d9bff1a2195a09 #mongo:6.0@sha256:594e2842e1bb62dcf35f892739192f897cf730ae5211e20b11693c18fb6a7e38
    container_name: mongo
    restart: on-failure
    command: '--replSet overleaf'
    volumes:
      - ${APP_DATA_DIR}/data/mongo_data:/data/db
      - ${APP_DATA_DIR}/data/server-ce/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex

  redis:
    image: redis:7.4@sha256:ca65ea36ae16e709b0f1c7534bc7e5b5ac2e5bb3c97236e4fec00e3625eb678d
    container_name: redis
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis_data:/data
