services:
  vert:
    container_name: vert
    image: ghcr.io/vert-sh/vert:latest
    environment:
      - PUB_HOSTNAME=umbrel-2.local:8732
      - PUB_PLAUSIBLE_URL=${PUB_PLAUSIBLE_URL:-https://plausible.example.com}
      - PUB_ENV=${PUB_ENV:-production}
      - PORT=3000
      - PUB_VERTD_URL=${PUB_VERTD_URL:-https://vertd.vert.sh}
    restart: unless-stopped
    ports:
      - 8732:80
