services:
  enclosed:
    image: corentinth/enclosed
    ports:
      - 8525:8787
    volumes:
      - ${APP_DATA_DIR}/data/enclosed-data:/app/.data
    restart: on-failure

volumes:
  enclosed-data:
    driver: local
