version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-qbittorrent_app_1
      APP_PORT: 8880

  app:
    image: ghcr.io/hotio/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Athens
      - WEBUI_PORTS=8880/tcp,8880/udp
      - VPN_ENABLED=false #
      - VPN_CONF=wg0 # READ THIS
      - VPN_PROVIDER=generic #
      - VPN_LAN_NETWORK=192.168.1.0/24 #
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_EXPOSE_PORTS_ON_LAN #
      - VPN_AUTO_PORT_FORWARD=false #
      - VPN_AUTO_PORT_FORWARD_TO_PORTS= #
      - VPN_KEEP_LOCAL_DNS=false #
      - VPN_FIREWALL_TYPE=auto #
      - VPN_HEALTHCHECK_ENABLED=false
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false #
    volumes:
      - /home/umbrel/umbrel/app-data/qbittorrent/data/config:/config
      - /home/umbrel/umbrel/home/Downloads:/downloads
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1 #
      - net.ipv6.conf.all.disable_ipv6=1 #
    devices:
      - /dev/net/tun:/dev/net/tun # OPTIONAL, READ THIS
    restart: on-failure
