version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-grav_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: linuxserver/grav:1.7.48@sha256:4220a4d60e8b27fcfcab649a79ffce0fface7c3d00b8b79197ace43afb809783
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 80:8888
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
