version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-postiz_web_1
      APP_PORT: 5000

  web:
    image: ghcr.io/gitroomhq/postiz-app:v1.36.1-amd64@sha256:ee0f880f52d81751077f630b8d0c8d7b8f010f637bb18f389264aa2adfa99b5f
    restart: on-failure
    environment:
      MAIN_URL: "http://umbrel-2.local:5555"
      FRONTEND_URL: "http://umbrel-2.local:5555"
      NEXT_PUBLIC_BACKEND_URL: "http://umbrel-2.local:5555/api"
      JWT_SECRET: "1VNJhz1fj1INZubVWE0KXCN9zhCCFL5mN7blCFDCH6k="
      DATABASE_URL: "postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GEN: "true"
      NOT_SECURED: "true"
    volumes:
      - ${APP_DATA_DIR}/data/postiz-config:/config
      - ${APP_DATA_DIR}/data/postiz-uploads:/uploads

  postiz-postgres:
    image: postgres:17-alpine@sha256:7062a2109c4b51f3c792c7ea01e83ed12ef9a980886e3b3d380a7d2e5f6ce3f5
    container_name: postiz-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postiz-user
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_DB: postiz-db-local
    volumes:
      - ${APP_DATA_DIR}/data/postgres-volume:/var/lib/postgresql/data

  postiz-redis:
    image: redis:7.4.2@sha256:bd41d55aae1ecff61b2fafd0d66761223fe94a60373eb6bb781cfbb570a84079
    container_name: postiz-redis
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis-volume:/data

volumes:
  postiz-config:
  postiz-uploads:
  postgres-volume:
  redis-volume:
