version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-livebook_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/livebook-dev/livebook:0.15.4@sha256:b23ef5c68de63132ebaa12e0b3120169074d932a8e6fc5bbce99b32aaf1c4299
    user: 0:0
    ports:
      - 8371:8081
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      LIVEBOOK_PORT: 8080
      LIVEBOOK_IP: 0.0.0.0
      LIVEBOOK_TOKEN_ENABLED: 0
      LIVEBOOK_PASSWORD: umbrel-livebook
    restart: on-failure
