version: "3"
services:
  app_proxy:
    environment:
      APP_HOST: denny-octobot_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

web:
  image: drakkarsoftware/octobot:2.0.6@sha256:5c35d59d3cb687dd1147d9b1d2d926c15cfde2cc8b3ce58df20f2ca9e623318e
    volumes:
       - ${APP_DATA_DIR}/logs:/octobot/logs
       - ${APP_DATA_DIR}/backtesting:/octobot/backtesting
       - ${APP_DATA_DIR}/tentacles:/octobot/tentacles
       - ${APP_DATA_DIR}/user:/octobot/user
    restart: on-failure

  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - ${APP_DATA_DIR}/var/run/docker.sock:/var/run/docker.sock
