version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-unifi_web_1
      APP_PORT: 8443

  web:
    image: ghcr.io/linuxserver/unifi-network-application:9.0.114@sha256:08c141dc6ba08fe05db01306ab633ac0478ef8677a1f308ef73bc3342f6f02f1
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MONGO_USER=unifi
      - MONGO_PASS=password
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 
      - MEM_STARTUP=1024 
      # MONGO_TLS=
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8893:8080
      - 1900:1900/udp 
      - 8843:8843 
      - 8880:8880 
      - 6789:6789 
      - 5514:5514/udp
    volumes:
      - ${APP_DATA_DIR}/data/unify_data:/config
    depends_on:
      - unifi-db

  unifi-db:
    image: mongo:latest
    container_name: unifi-db
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: unifi
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ${APP_DATA_DIR}/data/db_data:/data/db
