version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-lemmy_server_1
      APP_PORT: 8536

  server:
    image: dockurr/lemmy
    environment:
      RUST_LOG: "warn"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/lemmy.hjson:/config/config.hjson
