version: "3.9"

services:
  db:
    image: postgres:16
    command:
      [
        "postgres",
        "-c",
        "session_preload_libraries=auto_explain",
        "-c",
        "auto_explain.log_min_duration=5ms",
        "-c",
        "auto_explain.log_analyze=true",
        "-c",
        "track_activity_query_size=1048576"
      ]
    container_name: Lemmy-DB
    hostname: lemmy-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "lemmy", "-U", "lemmyuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/lemmy/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: lemmy
      POSTGRES_USER: lemmyuser
      POSTGRES_PASSWORD: lemmypass
    restart: on-failure:5

  pictrs:
    image: asonix/pictrs:0.5.0-rc.2
    container_name: Lemmy-PICTRS
    hostname: lemmy-pictrs
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    healthcheck:
      test: stat /etc/passwd || exit 1
    volumes:
      - /volume1/docker/lemmy/pictrs:/mnt:rw
    environment:
      PICTRS_OPENTELEMETRY_URL: http://otel:4137
      RUST_LOG: debug
      RUST_BACKTRACE: full
      PICTRS__MEDIA__VIDEO_CODEC: vp9
      PICTRS__MEDIA__GIF__MAX_WIDTH: 256
      PICTRS__MEDIA__GIF__MAX_HEIGHT: 256
      PICTRS__MEDIA__GIF__MAX_AREA: 65536
      PICTRS__MEDIA__GIF__MAX_FRAME_COUNT: 400
    restart: on-failure:5

  lemmy-back:
    image: dessalines/lemmy:0.19.3
    container_name: Lemmy-BACK
    hostname: lemmy-back
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    volumes:
      - /volume1/docker/lemmy/config.hjson:/config/config.hjson:ro
    environment:
      RUST_LOG: "warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
      RUST_BACKTRACE: full
    restart: on-failure:5
    depends_on:
      pictrs:
        condition: service_healthy
      db:
        condition: service_healthy

  lemmy-front:
    image: dessalines/lemmy-ui:0.19.3
    container_name: Lemmy-FRONT
    hostname: lemmy-front
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: false
    user: 1000:1000
    ports:
      - 8536:1234
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:1234
    environment:
      LEMMY_UI_LEMMY_INTERNAL_HOST: lemmy-back:8536
      LEMMY_UI_LEMMY_EXTERNAL_HOST: http://umbrel.local:8536
      LEMMY_HTTPS: false
    restart: on-failure:5
    depends_on:
      lemmy-back:
        condition: service_started
