version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: dockurr/lemmy-ui
      APP_PORT: 1234

  server:
    image: dockurr/lemmy
    environment:
      - LEMMY_UI_HTTPS=false
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=umbrel.local
    restart: on-failure
    stop_grace_period: 1m
