version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-gopeed_web_1
      APP_PORT: 9999

  web:
    image: liwei2633/gopeed
    restart: on-failure
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - ${APP_DATA_DIR}/data/Downloads:/app/Downloads
      - ${APP_DATA_DIR}/data/storage:/app/storage
