version: "3"

services:
  app_proxy:
    environment:
      APP_HOST: imp-wbo_server_1
      APP_PORT: 80

  server:
    volumes:
      - ${APP_DATA_DIR}/wbo-boards:/opt/app/server-data
    image: lovasoa/wbo:v1.20.1@sha256:169e32d669236fee1cb7e6dd85387362f1d69e33c16f85987301fd63bc479519
    environment:
      - UID=1000
      - GID=1000
    restart: on-failure
    stop_grace_period: 1m

  volume-permissions-fixer:
    image: bash:4.4@sha256:dbfd09bd48620c7899ae3363241643abba67949ae775f017a3cf94dfcbe80eac
    command: chown 1000:1000 -R /opt/app/server-data
    volumes:
      - ${APP_DATA_DIR}/wbo-boards:/opt/app/server-data
