version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-dashy_web_1
      APP_PORT: 8080

  web:
    image: lissy93/dashy:3.x@sha256:1072a49fd5736c1453b23870653ed89f39a02b00b73ce2c70bfe8c2280feedf0
    environment:
      - UID=1000
      - GID=1000
      - NODE_ENV=production
      # VUE_APP_TITLE=''
    restart: on-failure
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ${APP_DATA_DIR}/data/config/config.yml:/app/user-data/conf.yml:rw
      - ${APP_DATA_DIR}/data/icons:/app/user-data/item-icons/
