version: "3.9"
services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:v1.4.8@sha256:e6ccef307ebeadac967de0565b75e4906615ecfaac2a8f6bb82be13f111439d5
    container_name: swingmusic
    volumes:
      - ${APP_DATA_DIR}/music:/music
      - ${APP_DATA_DIR}/config:/config
    ports:
      - "1970:1970"
    restart: on-failure
