
version: '3.9'

services:
  app_proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "8437:80"  # Externer Port ist 8437
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    entrypoint: ["sh", "-c", "./update_nginx.sh && nginx -g 'daemon off;'"]

  web:
    image: davidjosearaujo/onionshare:0.0.1@sha256:49db7ad49e383590f83512b4607b135861ef9b74d4e2400ef53b9cd31f4d0d3b
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/onionshare-data:/onionshare
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
