version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: denny-linkstack_linkstack_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
      
  linkstack:
    image: linkstackorg/linkstack:latest # This image has no version specific tags
    restart: on-failure
    environment:
      SERVER_ADMIN: "" # Optional: Add your email or leave empty
      HTTP_SERVER_NAME: umbrel.local
      HTTPS_SERVER_NAME: "" # Optional: Add HTTPS server name or leave empty
    volumes:
      - ${APP_DATA_DIR}/data:/htdocs

volumes:
  linkstack_data:
