version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: denny-linkstack_linkstack_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
      
  linkstack:
    image: linkstackorg/linkstack:V4@sha256:5cc5b4806f57c153e924fbd0c49d4255dee4c66cd6621f0e457fd43e43e5c000
    restart: on-failure
    # This image doesn't support a custom user
    # user: '1000:1000'
    environment:
      SERVER_ADMIN: 
      HTTP_SERVER_NAME: umbrel.local
      HTTPS_SERVER_NAME:
    volumes:
      - ${APP_DATA_DIR}/data:/htdocs
    
volumes:
  linkstack_data:
