version: "3.8"

services:

  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest@sha256:6e7e8f44099f7c4f1340bb9ffda5411f97da766a06fd63cf1ff90c57ce22dd61
    environment:
      TZ: 'Europe/Berlin'
      #SERVER_ADMIN: 'admin@example.com'
      HTTP_SERVER_NAME: umbrel.local
      #HTTPS_SERVER_NAME: 'example.com'
      #LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '512M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - ${APP_DATA_DIR}/linkstack_data:/htdocs
    ports:
      - '8190:80'
    restart: on-failure

volumes:
  linkstack_data:
