version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-mastodon_web_1
      APP_PORT: 80

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: mastodon
      POSTGRES_DB: mastodon
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:7
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    restart: on-failure

  web:
    image: linuxserver/mastodon:4.3.3@sha256:bc2c0b7ef6e769943ab97d57a9a0cb40f4811134cc0bd8286a32d3db3c337b95
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - LOCAL_DOMAIN=example.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=mastodon
      - DB_PORT=5432
      - ES_ENABLED=false
      - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=fkSxKD2bF396kdQbrP1EJ7WbU7ZgNokR
      - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=r0hvVmzBVsjxC7AMlwhOzmtc36ZCOS1E
      - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=PhdFyyfy5xJ7WVd2lWBpcPScRQHzRTNr
      - SECRET_KEY_BASE=
      - OTP_SECRET=574bc695410efa19106e3b4d1af562c53ca346366e921d94cc9143a1d58d77ee
      - VAPID_PRIVATE_KEY=
      - VAPID_PUBLIC_KEY=
      - SMTP_SERVER=mail.example.com
      - SMTP_PORT=25
      - SMTP_LOGIN=
      - SMTP_PASSWORD=
      - SMTP_FROM_ADDRESS=notifications@example.com
      - S3_ENABLED=false
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/public:/live/public/system
    restart: on-failure
    depends_on:
      - db
      - redis
