version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-mastodon_web_1
      APP_PORT: 80

  web:
    image: linuxserver/mastodon:4.3.3@sha256:bc2c0b7ef6e769943ab97d57a9a0cb40f4811134cc0bd8286a32d3db3c337b95
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - LOCAL_DOMAIN=example.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=mastodon
      - DB_PORT=5432
      - ES_ENABLED=false
      - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=
      - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=
      - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=
      - SECRET_KEY_BASE=
      - OTP_SECRET=
      - VAPID_PRIVATE_KEY=
      - VAPID_PUBLIC_KEY=
      - SMTP_SERVER=mail.example.com
      - SMTP_PORT=25
      - SMTP_LOGIN=
      - SMTP_PASSWORD=
      - SMTP_FROM_ADDRESS=notifications@example.com
      - S3_ENABLED=false
      # WEB_DOMAIN=mastodon.example.com #optional
      # ES_HOST=es #optional
      # ES_PORT=9200 #optional
      # ES_USER=elastic #optional
      # ES_PASS=elastic #optional
      # S3_BUCKET= #optional
      # AWS_ACCESS_KEY_ID= #optional
      # AWS_SECRET_ACCESS_KEY= #optional
      # S3_ALIAS_HOST= #optional
      # SIDEKIQ_ONLY=false #optional
      # SIDEKIQ_QUEUE= #optional
      # SIDEKIQ_DEFAULT=false #optional
      # SIDEKIQ_THREADS=5 #optional
      # DB_POOL=5 #optional
      # NO_CHOWN= #optional
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure