version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-luanti_web_1
      APP_PORT: 30000

  web:
    image: linuxserver/luanti:5.11.0@sha256:007733ec735adc95e6da263c6165a52d29eee35cf6865433f91a105bd3b3d064
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/minetest_conf:/config/.minetest
    ports:
      - "30000:30000/udp"
      - "30001:30001/tcp"  # Web-UI-Port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000"]
      interval: 30s
      timeout: 10s
      retries: 3

  webui:
    image: ghcr.io/minetest-tools/minetest-webui:latest
    restart: unless-stopped
    environment:
      - MINETEST_HOST=web
      - MINETEST_PORT=30000
    ports:
      - "30002:8080"  # Web-Interface Ã¼ber Port 30002 erreichbar
    depends_on:
      - web
