version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-monica_web_1
      APP_PORT: 80

  web:
    image: monica:4.1.2@sha256:b1b332533066ac3d8daddc58acdcbe0feeeb8ea6dd983c27d316eb6e04e90571
    environment:
      - APP_ENV=local
      - APP_URL=http://umbrel-2.local:8559
      - FORCE_SSL=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=monica
      - APP_ENV=production
      - APP_TRUSTED_PROXIES=*
      # MAIL_MAILER=smtp
      # MAIL_HOST=smtp.gmail.com
      # MAIL_PORT=587
      # MAIL_USERNAME=Your-own-gmail-address
      # MAIL_PASSWORD=Your-own-app-password
      # MAIL_ENCRYPTION=tls
      # MAIL_FROM_ADDRESS=Your-own-gmail-address
      # MAIL_FROM_NAME=Monica
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/monica:/var/www/html/storage:rw

  db:
    container_name: Monica-DB
    image: mariadb:11.4-noble@sha256:5dfb3093333fa0ea53194ddef0a2bfa21d3b1e1353bd228b22610cd6fc0c04da
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: monica
      MYSQL_USER: monica
      MYSQL_PASSWORD: monica
      TZ: Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql:rw
    restart: on-failure
