version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-monica_web_1
      APP_PORT: 80

  web:
    image: linuxserver/monica:4.1.2@sha256:1b27f97939f0a3d41f89b5170471e67d2f962970bf583b1f68cf610016c4e1f3
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - APP_TRUSTED_PROXIES=*
      - DB_HOST=db
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/monica:/var/www/html/storage:rw

  db:
    image: mariadb:11.4-noble@sha256:5dfb3093333fa0ea53194ddef0a2bfa21d3b1e1353bd228b22610cd6fc0c04da
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql:rw
    restart: on-failure
