version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-briefkasten_web_1
      APP_PORT: 3000

  web:
    image: ndom91/briefkasten:sha-a37d2dc@sha256:c5ad2df826b3c69292373912e5dfccc4f6b650fad4a3c07fbcd11a22db7c98ed
    restart: on-failure
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://bkAdmin:briefkasten@postgres:5432/briefkasten?sslmode=disable
      - NEXTAUTH_SECRET=${APP_SEED}
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:3852
    depends_on:
      - postgres

  postgres:
    image: postgres:17.3@sha256:6e3358e46e34dae6c184f48fd06fe1b3dbf958ad5b83480031907e52b9ec2a7d
    restart: on-failure
    environment:
      - POSTGRES_DB=briefkasten
      - POSTGRES_USER=bkAdmin
      - POSTGRES_PASSWORD=briefkasten
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bkAdmin"]
      interval: 5s
      timeout: 3s
      retries: 5
