version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-naio_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  
  web:
    image: nextcloud/all-in-one:latest
    restart: on-failure
    container_name: nextcloud-aio-mastercontainer 
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    network_mode: host
volumes: 
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer 
