version: "3.9"
services:
  pixelfed-redis:
    image: redis
    container_name: Pixelfed-REDIS
    hostname: pixelfed-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 0:0
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - /volume1/docker/pixelfed/redis:/data:rw
    restart: on-failure:5

  pixelfed-db:
    image: postgres:16
    container_name: Pixelfed-DB
    hostname: pixelfed-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "pixelfeddb", "-U", "pixelfeduser"]
      timeout: 45s
      interval: 10s
      retries: 10
    env_file:
      - .env
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - /volume1/docker/pixelfed/db:/var/lib/postgresql/data:rw
    restart: on-failure:5

  pixelfed-web:
    image: quay.io/zknt/pixelfed:latest
    container_name: Pixelfed-WEB
    hostname: pixelfed-web
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: stat /etc/passwd || exit 1
    env_file:
      - .env
    volumes:
      - /volume1/docker/pixelfed/storage:/var/www/storage:rw
      - app-bootstrap:/var/www/bootstrap
    ports:
      - 9757:80
    restart: on-failure:5
    depends_on:
      pixelfed-db:
        condition: service_started
      pixelfed-redis:
        condition: service_healthy

  pixelfed-worker:
    image: quay.io/zknt/pixelfed:latest
    container_name: Pixelfed-WORKER
    hostname: pixelfed-worker
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: php artisan horizon:status | grep running
      interval: 60s
      timeout: 5s
      retries: 1
    env_file:
      - .env
    volumes:
      - /volume1/docker/pixelfed/storage:/var/www/storage:rw
      - app-bootstrap:/var/www/bootstrap
    restart: on-failure:5
    entrypoint: /worker-entrypoint.sh
    depends_on:
      pixelfed-db:
        condition: service_started
      pixelfed-redis:
        condition: service_healthy
      pixelfed-web:
        condition: service_healthy
volumes:
  app-bootstrap:
