version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-mumble_server_1
      APP_PORT: 64738

  server:
    image: mumblevoip/mumble-server:v1.5.634@sha256:11169b76bc418b414a3cb170694a4245ed51025fa0cba765886b28a8dff0dd97
    volumes:
      - ${APP_DATA_DIR}/data/mumble:/data:rw
    restart: on-failure
    user: "1000:1000"
    environment:
      - MUMBLE_CHOWN_DATA=false
      - MUMBLE_ACCEPT_UNKNOWN_SETTINGS=true

    
    #       expose:
    #           - 6502
