version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-mumble_web_1
      APP_PORT: 8080

  server:
    image: mumblevoip/mumble-server:v1.5.634@sha256:11169b76bc418b414a3cb170694a4245ed51025fa0cba765886b28a8dff0dd97
    restart: on-failure
    user: "1000:1000"
    environment:
      - MUMBLE_SUPERUSER_PASSWORD=umbrel
    volumes:
      - ${APP_DATA_DIR}/data/mumble:/data:rw
    ports:
      - "64738:64738"
      - "64738:64738/udp"

  web:
    image: leoverto/mumble-web:latest@sha256:9590ed597b295adebe9be0b08a99e5dc8fe1651f8fcd90dc50038c0ec40366f3
    restart: on-failure
    user: "1000:1000"
    environment:
      - MUMBLE_SERVER=server:64738
