version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-stremio_server_1
      APP_PORT: 8080

  server:
    image: tsaridas/stremio-docker:latest
    ports:
      - 12470:12470
    environment:
      - NO_CORS=1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/root/.stremio-server
