version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-stremio_server_1
      APP_PORT: 11470

  server:
    image: stremio/server:latest
    ports:
      - 12470:12470
    environment:
      - FFMPEG_BIN=/bin/ffmpeg
      - FFPROBE_BIN=/bin/ffprobe
      - NO_CORS=1
      #- APP_PATH=""
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/bin/ffmpeg:/bin/ffmpeg:ro
      - ${APP_DATA_DIR}/data/bin/ffprobe:/bin/ffprobe:ro
