version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-koel_server_1
      APP_PORT: 80

  server:
    image: phanan/koel:7.2.1@sha256:f3be4da3fde5e5b46d8a215860e11db8eb38e0320633abc3b8e6235bd4322a2d
    depends_on:
      - database
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_USERNAME=koel
      - DB_PASSWORD=umbrel
      - DB_DATABASE=koel
      - TRANSCODE_FLAC=false
      - FORCE_HTTPS=true
    volumes:
      - ${APP_DATA_DIR}/data/music:/music:rw
      - ${APP_DATA_DIR}/data/covers:/var/www/html/public/img/covers:rw
      - ${APP_DATA_DIR}/data/search_index:/var/www/html/storage/search-indexes:rw
    entrypoint: /bin/sh -c "sleep 15 && php artisan koel:init && apache2-foreground"  # Warte 15 Sekunden und initialisiere die DB

  database:
    image: mariadb:10.11@sha256:3958f2df725a9ebdabd0ae6a0c0a841da8e45194b36a33d8bd83abb7dd6c034a
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=umbrel
      - MYSQL_DATABASE=koel
      - MYSQL_USER=koel
      - MYSQL_PASSWORD=umbrel

networks:
  default:
    driver: bridge
