version: '3'

services:
  koel:
    image: phanan/koel:7.2.0@sha256:f9e23069a4f90b2ac2dfde2ce05e788a1c362d08b0494bc7eaead377572b209f
    depends_on:
      - database
    ports:
      - 8333:80
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=koel
      - DB_PASSWORD=admin
      - DB_DATABASE=koel
    volumes:
      - ${APP_DATA_DIR}/data/music:/music:rw
      - ${APP_DATA_DIR}/data/covers:/var/www/html/public/img/covers:rw
      - ${APP_DATA_DIR}/data/search_index:/var/www/html/storage/search-indexes:rw

  database:
    image: postgres:13@sha256:a4c9ad5add8a2e4c86e123bfdaf940d120c0541b782f317ab4e630ab3d391650
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=koel
      - POSTGRES_USER=koel
      - POSTGRES_PASSWORD=admin

volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local
