version: '3.7'

services:
  db:
    image: linuxserver/mariadb:11.4.4@sha256:fdf30e6b302688c290cef10ca24b80e6e25e93955bc6b64636777f06676a6c52
    volumes:
      - ${APP_DATA_DIR}/data/dbvol:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: punyshort
      MYSQL_DATABASE: punyshort
      MYSQL_USER: punyshort
      MYSQL_PASSWORD: punyshort

  backend:
    depends_on:
      - db
    image: interaapps/punyshort-backend:beta-1.0.9@sha256:b727e80a65f10aa6fb2fabac7965de6e6f452488b2f46ceec24ccc374bca2024
    ports:
      - "9581:80"
      
    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: mysql
      DATABASE_NAME: punyshort
      DATABASE_USER: punyshort
      DATABASE_PASSWORD: punyshort
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      SERVER_NAME: "https://{SERVER}:81"
      OAUTH2_PROVIDER_CLIENT_ID: {CLIENT_ID}
      OAUTH2_PROVIDER_CLIENT_SECRET:
      PUNYSHORT_DEFAULT_REDIRECT_PROXY:
      PUNYSHORT_DEFAULT_CNAME:

  frontend:
    depends_on:
      - backend
    image: interaapps/punyshort-frontend:beta-1.0.8@sha256:35e941895820b891a53220c6b791d510d0801792755e523a041ea27b056f7b77
    ports:
      - "9580:80"
      
    environment:
      PUNYSHORT_FRONTEND_API: https://{SERVER}:81
      PUNYSHORT_FRONTEND_CLIENT_ID: CLIENT_ID

  redirect_proxy:
    depends_on:
      - backend
    image: interaapps/punyshort-redirect-proxy:beta-1.0.0@sha256:cf3179857327a3610e59351fa66fa61fadcf47569da2aa2b82d198122af9ea77
    ports:
      - "9583:80"
      
    environment:
      PUNYSHORT_BASE_URL: http://db:81
      PUNYSHORT_KEY: API_KEY
      PUNYSHORT_ERROR_URL: https://{SERVER}:81/error-page
      PUNYSHORT_IP_FORWARDING: true
  

volumes:
  dbvol: