services:
  statusnook:
    ports:
      - 0.0.0.0:8444:8000
    volumes:
      - ${APP_DATA_DIR}/statusnook-data:/app/statusnook-data
    restart: always
    image: goksan/statusnook:latest@sha256:9b2c87213312b1856d52d576d7512aeae71190437b502739f352feba0bcc12e0
volumes:
  statusnook-data:
    name: statusnook-data
