version: '3'
services:
    db:
        image: postgres:16
        volumes:
            - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=umbrel
            - POSTGRES_USER=umbrel
            - POSTGRES_DB=joplindb
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: on-failure
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://umbrel.local:22300
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=umbrel
            - POSTGRES_DATABASE=joplindb
            - POSTGRES_USER=umbrel
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
