version: '3.7'

services:
  db:
    image: postgres:13
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/joplin/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: joplin
      POSTGRES_PASSWORD: joplinpass
      POSTGRES_DB: joplin
    networks:
      - joplin-network

  app:
    image: joplin/server:latest@sha256:52af57880c0e04a179107807e13ffb8868b31ea2cc86a2b04da42220facb7589
    restart: on-failure
    ports:
      - 22300:80
    environment:
      APP_BASE_URL: http://umbrel.local
      DB_CLIENT: pg
      POSTGRES_PASSWORD: joplinpass
      POSTGRES_DATABASE: joplin
      POSTGRES_USER: joplin
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      JOPLIN_EMAIL: admin@localhost
      JOPLIN_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - ${APP_DATA_DIR}/data/joplin:/var/lib/joplin
    networks:
      - joplin-network

networks:
  joplin-network:
    driver: bridge
