version: '3.9'

  services:
    app_proxy:
      environment:
        APP_HOST: denny-slash_web_1
        APP_PORT: 5231
        PROXY_AUTH_ADD: "false"

    web:
      image: yourselfhosted/slash:1.0.0@sha256:4d1ca12f0c5e1701cf8d7140f25bd247bdad4ab5711432e06b4c8cc8993b76ea
      restart: on-failure
      volumes:
        - ${APP_DATA_DIR}/slash:/var/opt/slash

volumes:
  slash:
