server_url: http://umbrel.local:8085
listen_addr: 0.0.0.0:8085
grpc_listen_addr: 0.0.0.0:50443
private_key_path: /etc/headscale/private.key
noise:
  private_key_path: /etc/headscale/noise_private.key   # FÃ¼gt die noise.private_key_path Konfiguration hinzu
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite
log_level: info

dns:
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8

magic_dns: true
node_update_check: true

# Web UI Config
ui:
  base_path: /web
  listen_addr: 0.0.0.0:8383
  enable: true
