version: '3.7'

services:
  openhab:
    image: "openhab/openhab:4.2.2@sha256:8ddbadca555dbc49ff9166d4ccca1e0f146bd2a1bcb8c3fac43df40b2df78568"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${APP_DATA_DIR}/openhab_addons:/openhab/addons"
      - "${APP_DATA_DIR}/openhab_conf:/openhab/conf"
      - "${APP_DATA_DIR}/openhab_userdata:/openhab/userdata"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      OPENHAB_HTTP_PORT: "8780"
      OPENHAB_HTTPS_PORT: "8743"
