version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-rustdesk_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/linuxserver/rustdesk:1.3.7@sha256:96c9e2551b51006e6536dff733eb860f14c1d480e6ea0db9fe32c4a19fa4330a
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${APP_DATA_DIR}/data/tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 3045:3001
    restart: on-failure
