version: '3.9'
services:
  db:
    image: mysql:5.7
    volumes:
      - ${APP_DATA_DIR}/data/solidinvoicedb:/var/lib/mysql:rw
    security_opt:
      - no-new-privileges:true
    restart: on-failure
    environment:
      MYSQL_DATABASE: solidinvoice
      MYSQL_ROOT_PASSWORD: umbrel
      MYSQL_USER: solidinvoice
      MYSQL_PASSWORD: umbrelpass
    container_name: denny-solidinvoice_db_1
  app:
    image: solidinvoice/solidinvoice:latest
    depends_on:
      - db
    ports:
      - '5484:80'
    restart: on-failure
    container_name: denny-solidinvoice_app_1
