version: '3.9'
services:
  db:
    image: mysql:5.7
    volumes:
      - ${APP_DATA_DIR}/data/solidinvoicedb:/var/lib/mysql:rw
    security_opt:
      - no-new-privileges:true
    restart: on-failure
    environment:
      MYSQL_DATABASE: solidinvoice
      MYSQL_ROOT_PASSWORD: umbrelpass
      MYSQL_USER: solidinvoice
      MYSQL_PASSWORD: umbrelpass
  app:
    image: solidinvoice/solidinvoice:2.2.6@sha256:e7f16147dff124f023eed3e833e8b52da82b786e6fe5bd8ddd40e5bf885dafa0
    depends_on:
      - db
    ports:
      - 5484:80
    restart: on-failure
