version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-crafty_web_1
      APP_PORT: 8000

  web:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.4.7@sha256:a2a083675b1e6442599e31dba230f2242c9f9c713e360a507ee7df205ab4689f
    ports:
      - "18443:8443" 
      - "18123:8123" 
      - "19132:19132/udp" 
      - "25500-25600:25500-25600" 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/backups:/crafty/backups
      - ${APP_DATA_DIR}/data/logs:/crafty/logs
      - ${APP_DATA_DIR}/data/servers:/crafty/servers
      - ${APP_DATA_DIR}/data/config:/crafty/app/config
      - ${APP_DATA_DIR}/data/import:/crafty/import
    restart: on-failure