version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-rstudio_web_1
      APP_PORT: 8787

  web:
    image: ghcr.io/rocker-org/rstudio:4.4.2@sha256:050e232046d8a8681d84444498a48afadfa7900fa783be5ec3ed9f4eb9f3ceb0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/rstudio
    environment:
      PASSWORD: "umbrel"
