version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-noflux_web_1
      APP_PORT: 8080

  web:
    image: fiatjaf/noflux:0.1.0@sha256:13bdc84ee27d28fb456d2de52a9a398e6567fefbe2dc63aadc5c9ced35b2a665
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://noflux:secret@db/noflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=noflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=noflux
    volumes:
      - noflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "noflux"]
      interval: 10s
      start_period: 30s
volumes:
  noflux-db:
