version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-akaunting_web_1
      APP_PORT: 80

  web:
    image: akaunting/akaunting:3.1.17@sha256:93749634bb7c8df4dfd88c9179e2a0cb2a3752294b6d53ab0bc344720bdc2044
    restart: on-failure
    env_file:
      - ${APP_DATA_DIR}/data/env/run.env
    environment:
      - AKAUNTING_SETUP
    volumes:
      - ${APP_DATA_DIR}/data/akaunting-data:/var/www/html:rw
      - ${APP_DATA_DIR}/data/httpd/custom_httpd.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mariadb:latest@sha256:81e893032978c4bf8ad43710b7a979774ed90787fa32d199162148ce28fe3b76
    volumes:
      - ${APP_DATA_DIR}/data/akaunting-db:/var/lib/mysql:rw
    restart: on-failure
    env_file:
      - ${APP_DATA_DIR}/data/env/db.env

volumes:
  akaunting-data:
  akaunting-db:
