version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-akaunting_web_1
      APP_PORT: 80

  web:
    image: akaunting/akaunting:3.1.17@sha256:93749634bb7c8df4dfd88c9179e2a0cb2a3752294b6d53ab0bc344720bdc2044
    environment:
      #APP_URL: http://${DEVICE_DOMAIN_NAME}:8773
      LOCALE: en-US
      DB_HOST: denny-akaunting-db_1
      DB_PORT: 3347
      DB_NAME: akaunting
      DB_USERNAME: admin
      DB_PASSWORD: akaunting_password
      DB_PREFIX: asd_
      #COMPANY_NAME: My Company
      #COMPANY_EMAIL: my@company.com
      ADMIN_EMAIL: admin@admin.admin
      ADMIN_PASSWORD: umbrel
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/akaunting-data:/var/www/html:rw
    depends_on:
      - db

  db:
    image: mariadb:latest@sha256:81e893032978c4bf8ad43710b7a979774ed90787fa32d199162148ce28fe3b76
    environment:
      MYSQL_DATABASE: akaunting
      MYSQL_USER: admin
      MYSQL_PASSWORD: akaunting_password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - "3347:3306"
    volumes:
      - ${APP_DATA_DIR}/data/akaunting-db:/var/lib/mysql:rw
    restart: on-failure
