version: '3.7'

services:
  headscale:
    container_name: headscale
    image: headscale/headscale:latest
    command: serve # F체hrt den Headscale-Dienst aus
    restart: unless-stopped
    ports:
        - 8380:8080 # Port f체r Headscale-Dienst ge채ndert auf 8380
        - 9299:9090 # Port f체r Monitoring/Metriken
    volumes:
      - ${APP_DATA_DIR}/config:/etc/headscale/
      - ${APP_DATA_DIR}/data:/var/lib/headscale

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    restart: unless-stopped
    ports:
        - 8383:80
