version: '3.7'

services:
  headscale:
    image: headscale/headscale:v0.24@sha256:2a2dcc9fef8f6e520a096743b668e3fd5df06ae422298c808c4e934a78764860
    container_name: headscale
    volumes:
      - ${APP_DATA_DIR}/config:/etc/headscale
      - ${APP_DATA_DIR}/data:/var/lib/headscale
    ports:
      - "8085:8080"
    command: serve
    restart: on-failure
    networks:
      - headscale-net  # Definiere das Netzwerk f√ºr Kommunikation

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:2025.01.20@sha256:dda8534d5bde03b35b5bd11def3409938ec265d08c431c43294632573a2f3ae3
    container_name: headscale-ui
    ports:
      - "8543:8443"  
      - "8383:8080"
    restart: on-failure
    environment:
      - HEADSCALE_API=http://headscale:8080  # Der URL zum Headscale API-Service
    networks:
      - headscale-net  # Das gleiche Netzwerk wie headscale

networks:
  headscale-net:  # Das Netzwerk, auf dem die Kommunikation zwischen den Containern stattfindet
    driver: bridge
