version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-nomie_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/linuxserver/altus:5.4.0@sha256:65387a1324bd2037c41fe270d5781000852b917f3e184739f46ed146d3178480
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    shm_size: "2gb"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config

#https://docs.linuxserver.io/images/docker-altus/#options-in-all-kasmvnc-based-gui-containers
