version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-nomie_web_1
      APP_PORT: 3000

  web:
    image: rogerrum/docker-nomie6-oss:6.3.0@sha256:b49550995d68e0cd0513ac54bac614912f88f779f6f538880e1139cf7b631b19
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s 
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    depends_on:
      - db

  db:
    image: couchdb:3.4.3@sha256:b5491a6cdf6417bf8762166a207380c5393e075020b3168fd958649b2417f24f
    ports:
      - 5985:5984
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5984' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s  
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: umbrel
    volumes:
      - ${APP_DATA_DIR}/data/db:/opt/couchdb/data:rw
