version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cobalt_web_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"
  web:
    image: dennysubke/cobalt:10.9@sha256:81b019316b9b87a082d4d9af5d10b5481b0d63c7cdadf62b5854195a2d312903
    read_only: true
    restart: on-failure
    user: "1000:1000"
    ports:
      - 9013:9000
    environment:
      API_URL: "http://${DEVICE_DOMAIN_NAME}:9013/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400
