version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cobalt_web_1
      APP_PORT: 9000
  web:
    image: ghcr.io/imputnet/cobalt:10.6@sha256:a2d11299d02bd8d2c5acc0a8e796f200037ea45e107607c4f477af09c34f3d2f
    init: true
    read_only: true
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/cookies/cookies.json:/cookies.json
      - 0.0.0.0:9000:9000
    environment:
      API_URL: "http://umbrel-2.local:9990/" 
      API_LISTEN_ADDRESS: "0.0.0.0"
