version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cobalt_web_1
      APP_PORT: 9001
  web:
    image: dennysubke/cobalt:10.6.1@sha256:d2973997e427f75aae5e567f94301c8797ae8d8e26b79f007aa7e5e7863a1ef2
    init: true
    read_only: true
    restart: on-failure
    ports:
      - 0.0.0.0:9000:9000
    environment:
      #WEB_HOST: "http://umbrel-2.local:9001/"
      #WEB_DEFAULT_API: "http://umbrel-2.local:9000/"
      API_URL: "http://umbrel-2.local:9000/"
      #API_AUTH_REQUIRED: 0
      #DURATION_LIMIT: 86400
    volumes:
      - ${APP_DATA_DIR}/data/cookies/cookies.json:/cookies.json
