version: "3"

services:
  docmost:
    image: docmost/docmost:0.4.1@sha256:d5ed81541e2b6de2b1c54ea5a06e1e9f198441da87074c6788ac1d77edad4bb5
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://umbrel.local:3626"
      APP_SECRET: 026faeff822cee62cbdda1c3ca5d7cab
      DATABASE_URL: "postgresql://docmost:umbrelpass@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3626:3000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: umbrelpass
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
