version: "3"

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://umbrel.local:3626"
      APP_SECRET: "REPLACE_WITH_LONG_SECRET"
      DATABASE_URL: "postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3626:3000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
