version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-sparrow_web_1
      APP_PORT: 80

  web:
    image: ghcr.io/sethforprivacy/sparrow-server:1.9.0
    restart: on-failure